name: Testador de Seletores

on:
  workflow_dispatch: # Permite que você ative o teste manualmente com um clique no painel do GitHub
  schedule:
    - cron: '0 8 * * 1' # Opcional: Roda automaticamente toda segunda-feira às 05:00h (horário de Brasília)

jobs:
  rodar-testes:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v4

      - name: Configurar Ambiente Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          # Removido o cache automático do pip para evitar o erro de falta de requirements.txt

      - name: Instalar Dependências do Robô
        run: |
          pip install --upgrade pip
          pip install playwright supabase python-dotenv pytz
          playwright install chromium

      - name: Criar Arquivo de Credenciais Temporário
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> credenciais_supabase.env
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> credenciais_supabase.env

      - name: Executar Script de Testes
        run: python teste_seletor.py
